%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera frames per second 
Camera.fps: 30.0

# stereo baseline times fx
Camera.bf: 80.01684

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
LEFT.height: 720
LEFT.width: 1280
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.295523, 0.076320, -0.000029, -0.000465, 0.000000]
LEFT.K: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [712.37134,   0.     , 632.83143,
           0.     , 712.44208, 341.77729,
           0.     ,   0.     ,   1.     ]
LEFT.R:
  rows: 3
  cols: 3
  dt: d
  data: [ 0.99983515, -0.0084335 , -0.01607968,
          0.00845202,  0.99996369,  0.00108397,
          0.01606995, -0.00121969,  0.99987013]
LEFT.P:
  rows: 3
  cols: 4
  dt: d
  data:  [656.6039 ,   0.     , 702.86692,   0.     ,
           0.     , 656.6039 , 335.0653 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]

RIGHT.height: 720
RIGHT.width: 1280
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.283335, 0.067309, 0.000220, 0.001275, 0.000000]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [706.62518,   0.     , 640.23503,
           0.     , 708.86142, 340.94987,
           0.     ,   0.     ,   1.     ]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.99858156, -0.00913186, -0.05245459,
          0.00907141,  0.99995789, -0.00139037,
          0.05246508,  0.00091256,  0.99862234]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [656.6039 ,   0.     , 702.86692, -80.01684,
           0.     , 656.6039 , 335.0653 ,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]


